import 'package:flutter/material.dart';

const baseUrl = 'http://www.dev-fusion.com/api/mobile/';
//URLs for Users collection APIs
const loginUrl = '${baseUrl}login';
const registerUrl = '${baseUrl}register';
const resendEmailUrl = '${baseUrl}resend_verification_email';
const updateUserUrl = '${baseUrl}users';
const resetPasswordUrl = '${baseUrl}users/password';
const getUserUrl = '${baseUrl}users/';
const forgotPasswordUrl = '${baseUrl}forgot_password';
const jwtUrl = '${baseUrl}jwtTest';
//URLs for Projects collection APIs
const getProjectUrl = '${baseUrl}project/';
const createProjectUrl = '${baseUrl}project';
const editTeamMembersUrl = '${baseUrl}project/team_members';
const discoverUrl = '${baseUrl}discover';
const ownedProjectsUrl = '${baseUrl}owned-projects';
const joinedProjectsUrl = '${baseUrl}joined-projects';
const ownedJoinedUrl = '${baseUrl}owned-joined';
const editProjectUrl = '${baseUrl}edit-project';
const deleteProjectUrl = '${baseUrl}project/';
const leaveProjectUrl = '${baseUrl}project/leave';
//URLs for Inbox collection APIs
const applyInboxUrl = '${baseUrl}inbox/apply';
const acceptInboxUrl = '${baseUrl}inbox/accept_member';
const rejectInboxUrl = '${baseUrl}inbox/reject_member';
const getInboxUrl = '${baseUrl}inbox/';

final List<Color> bubbleBgColors = [
  Color(0xffb91c1c), // bg-red-700
  Color(0xffc2410c), // bg-orange-700
  Color(0xffb45309), // bg-amber-700
  Color(0xffa16207), // bg-yellow-700
  Color(0xff4d7c0f), // bg-lime-700
  Color(0xff15803d), // bg-green-700
  Color(0xff047857), // bg-emerald-700
  Color(0xff0f766e), // bg-teal-700
  Color(0xff0e7490), // bg-cyan-700
  Color(0xff0369a1), // bg-sky-700
  Color(0xff1d4ed8), // bg-blue-700
  Color(0xff4338ca), // bg-indigo-700
  Color(0xff7e22ce), // bg-violet-700
  Color(0xffa21caf), // bg-purple-700
  Color(0xffbe185d), // bg-fuchsia-700
  Color(0xff9d174d), // bg-pink-700
  Color(0xffbe123c) // bg-rose-700
];

const technologies = [
  "Ada",
  "Adobe XD",
  "Airflow",
  "ALGOL",
  "Alpine.js",
  "Amazon DynamoDB",
  "Amazon EC2",
  "Amazon FreeRTOS",
  "Amazon RDS",
  "Amazon S3",
  "Ansible",
  "Apache Ant",
  "Apache Flink",
  "Apache Kafka",
  "Apache Spark",
  "Apache Storm",
  "Apache Tomcat",
  "APL",
  "Arduino",
  "ASP.NET",
  "Assembly",
  "Awk",
  "AWS",
  "AWS Lambda",
  "Azure",
  "Backbone.js",
  "Ballerina",
  "Bash",
  "BASIC",
  "Bitbucket",
  "Blender",
  "Blockchain",
  "Bootstrap",
  "Bower",
  "BPG (Border Gateway Protocol)",
  "Burp Suite",
  "C",
  "C#",
  "C++",
  "Caddy",
  "Caffe",
  "CakePHP",
  "Capistrano",
  "Cassandra",
  "Ceylon",
  "Chef",
  "Chainlink",
  "CircleCI",
  "Cisco Networking",
  "Clojure",
  "Cloudflare",
  "COBOL",
  "Cocos2d",
  "Coda",
  "CodeIgniter",
  "CoffeeScript",
  "Cognos",
  "Cordova",
  "CouchDB",
  "C++",
  "CrateDB",
  "CryEngine",
  "Crystal",
  "CSS3",
  "Cucumber",
  "D",
  "D3.js",
  "Dagger",
  "Dart",
  "Dask",
  "Databricks",
  "DataDog",
  "Delphi",
  "DigitalOcean",
  "Django",
  "Docker",
  "Dojo",
  "Druid",
  "Drupal",
  "Eclipse",
  "EdgeX Foundry",
  "Eiffel",
  "Elasticsearch",
  "Electron",
  "Elixir",
  "Elm",
  "Ember.js",
  "Erlang",
  "Express.js",
  "F#",
  "Facebook AI",
  "Falcon",
  "FastAPI",
  "Feathers.js",
  "Figma",
  "Firebase",
  "Flask",
  "Flutter",
  "Fortran",
  "FreeBSD",
  "Gatling",
  "GCP (Google Cloud Platform)",
  "Geany",
  "Gensim",
  "GIMP",
  "Git",
  "GitHub",
  "GitLab",
  "Gnuplot",
  "Go",
  "Google AI",
  "Google Analytics",
  "Google App Engine",
  "Google Cloud IoT",
  "Google Compute Engine",
  "Google Kubernetes Engine",
  "Google Tag Manager",
  "Gradle",
  "Grafana",
  "GraphQL",
  "Groovy",
  "Grunt",
  "Gulp",
  "Hadoop",
  "HAML",
  "Hapi.js",
  "Haskell",
  "Helm",
  "Heroku",
  "Hibernate",
  "Hive",
  "HTML5",
  "Hugo",
  "IBM Cloud",
  "IBM Watson",
  "IDL",
  "Io",
  "Ionic",
  "IPFS",
  "IPv6",
  "Jaeger",
  "Jasmine",
  "Java",
  "JavaScript",
  "Jenkins",
  "Jest",
  "JIRA",
  "JMeter",
  "Joomla",
  "JPA (Java Persistence API)",
  "JQuery",
  "JSON",
  "Julia",
  "Jupyter Notebooks",
  "Kafka",
  "Kali Linux",
  "Karma",
  "Keras",
  "Keycloak",
  "Kibana",
  "Koa",
  "Kotlin",
  "Kubernetes",
  "LabVIEW",
  "Laravel",
  "LESS",
  "Lighttpd",
  "LinkedIn Learning",
  "Linux",
  "Logstash",
  "Looker",
  "LoRaWAN",
  "Lua",
  "Magento",
  "MariaDB",
  "MATLAB",
  "Maven",
  "Maya",
  "Metasploit",
  "Meteor.js",
  "Microsoft Azure AI",
  "Microsoft Azure IoT",
  "Microsoft SQL Server",
  "MongoDB",
  "MonoGame",
  "MPLS",
  "MQTT",
  "MySQL",
  "Nagios",
  "NATS",
  "Neo4j",
  "Nest.js",
  "Nessus",
  "Next.js",
  "Nginx",
  "Nim",
  "NLTK",
  "Node.js",
  "NPM",
  "NumPy",
  "Nuxt.js",
  "Objective-C",
  "OCaml",
  "OpenAI GPT-3",
  "OpenCV",
  "OpenFlow",
  "OpenGL",
  "OpenID Connect",
  "OpenShift",
  "OpenStack",
  "Oracle DB",
  "OWASP ZAP",
  "Pandas",
  "Parcel",
  "Pascal",
  "Perl",
  "PHP",
  "Phoenix",
  "Piwik",
  "Polymer",
  "PostgreSQL",
  "PowerBI",
  "Premiere Pro",
  "Presto",
  "Prolog",
  "Puppet",
  "PureScript",
  "Pytorch",
  "Python",
  "Qlik",
  "Qt",
  "RabbitMQ",
  "Racket",
  "Raku",
  "Raspberry Pi",
  "React Native",
  "React.js",
  "Realm",
  "Redis",
  "Redux",
  "REXX",
  "Ripple",
  "Robotics Operating System (ROS)",
  "Rollbar",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "Sass",
  "Scala",
  "Scikit-learn",
  "Scrapy",
  "Scratch",
  "Selenium",
  "Sencha",
  "Sentry",
  "Silex",
  "Sinatra",
  "Sketch",
  "Slack",
  "Smarty",
  "Smalltalk",
  "Solidity",
  "SonarQube",
  "Spacy",
  "Spark",
  "Spring",
  "SQL",
  "SQLite",
  "SQS (Amazon Simple Queue Service)",
  "StatsD",
  "Stellar",
  "Stimulus",
  "Struts",
  "Stylus",
  "Svelte",
  "SVG",
  "Swagger",
  "Swift",
  "Symfony",
  "Tableau",
  "Tailwind CSS",
  "Tcl",
  "TensorFlow",
  "Terraform",
  "Thymeleaf",
  "Trello",
  "Truffle Suite",
  "Twilio",
  "TypeScript",
  "Ubuntu",
  "Unity",
  "Unreal Engine",
  "Vagrant",
  "Varnish",
  "VBScript",
  "Vercel",
  "VHDL",
  "Vim",
  "VirtualBox",
  "Visual Basic",
  "Vue.js",
  "W3C",
  "Webpack",
  "WebRTC",
  "WebSocket",
  "Wireshark",
  "WordPress",
  "WPF (Windows Presentation Foundation)",
  "Xamarin",
  "XML",
  "Yarn",
  "Yoast",
  "YouTrack",
  "Zephyr",
  "Zeplin",
  "Zig",
  "Zookeeper",
];

const roles = [
  "AI Engineer",
  "API Developer",
  "Application Developer",
  "Backend Developer",
  "Big Data Engineer",
  "Blockchain Developer",
  "Business Analyst",
  "Cloud Architect",
  "Cloud Engineer",
  "Computer Vision Engineer",
  "Cybersecurity Analyst",
  "Data Analyst",
  "Data Architect",
  "Data Engineer",
  "Data Scientist",
  "Database Administrator",
  "DevOps Engineer",
  "Embedded Systems Engineer",
  "Frontend Developer",
  "Full Stack Developer",
  "Game Developer",
  "Hardware Engineer",
  "Help Desk Technician",
  "Infrastructure Engineer",
  "IoT Engineer",
  "IT Consultant",
  "Machine Learning Engineer",
  "Mobile Developer",
  "Network Administrator",
  "Network Engineer",
  "Product Manager",
  "Project Manager",
  "QA Engineer",
  "Research Scientist",
  "Robotics Engineer",
  "Scrum Master",
  "Security Engineer",
  "Site Reliability Engineer",
  "Software Architect",
  "Software Developer",
  "Software Engineer",
  "Solutions Architect",
  "Support Engineer",
  "System Administrator",
  "Systems Analyst",
  "Test Engineer",
  "UI/UX Designer",
  "Web Developer",
];

const communications = [
  "Airtable",
  "Allo",
  "Amazon Chime",
  "AOL Instant Messenger",
  "Asana",
  "Basecamp",
  "Beekeeper",
  "Bitrix24",
  "Blink",
  "BlueJeans",
  "Box",
  "Breeze",
  "Buffer",
  "Campfire",
  "Chanty",
  "Cisco Webex",
  "ClickUp",
  "Clubhouse",
  "Confluence",
  "Dialpad",
  "Discord",
  "Dropbox",
  "Facebook Messenger",
  "Flock",
  "Flowdock",
  "Fuze",
  "Gitter",
  "Glip",
  "Google Chat",
  "Google Duo",
  "Google Hangouts",
  "Google Meet",
  "HipChat",
  "Hootsuite",
  "Houseparty",
  "iMessage",
  "Instagram",
  "Jabber",
  "Jitsi",
  "Jive",
  "Kik",
  "Kustomer",
  "Lark",
  "LinkedIn",
  "Loom",
  "Mattermost",
  "Microsoft Teams",
  "Miro",
  "Mural",
  "Nextcloud Talk",
  "Pexip",
  "Pumble",
  "Quip",
  "Redbooth",
  "RingCentral",
  "Ryver",
  "Salesforce Chatter",
  "Sametime",
  "SendBird",
  "Signal",
  "Skype",
  "Slack",
  "Snapchat",
  "Sococo",
  "Spark",
  "Stride",
  "Symphony",
  "Talkspirit",
  "TeamViewer",
  "Telegram",
  "Threema",
  "Threads",
  "Trello",
  "Trillian",
  "Troop Messenger",
  "Twist",
  "Twitter",
  "Viber",
  "Voxer",
  "Walkie",
  "WeChat",
  "WhatsApp",
  "Wickr",
  "Workplace by Facebook",
  "Yammer",
  "Yammer",
  "YouTube Live",
  "Zoho Cliq",
  "Zoho Meeting",
  "Zoom",
];

List<String> getTechnolgies(String techSearch) {
  List<String> techList = [];
  if (techSearch.length > 1) {
    techList = technologies
        .where((tech) => tech.toLowerCase().contains(techSearch.toLowerCase()))
        .toList();
  }
  return techList;
}

Color getBubbleColor(String text) {
  int hash = 0;

  for (int i = 0; i < text.length; i++) {
    hash += text.codeUnitAt(i);
  }

  return bubbleBgColors[hash % bubbleBgColors.length];
}

//Variables for Cloudinary
const cloudinaryUrl = 'https://api.cloudinary.com/v1_1/dlj2rlloi/upload';
const cloudinaryApiKey = '153675853953957';
const cloudinaryApiSecret = '7YD9MRHeaWC1UqF9r5uYAmjGMMA';
